qna_app/urls.py
from django.urls import path
#from .views import addquestion,popques,question,update_question
from qna_app import views
# from django.views.generic import QuestionModelCreateView


app_name='qna'

urlpatterns=[
    path('addquestion/',views.addquestion,name='add'),
    path('popques/',views.popques,name='popularques'),
    path('question/',views.question,name='question'),
    path('update/<int:id>/',views.update_question,name='update'),
    path('queslist',views.queslist,name='queslist'),
    path('del_ques/<int:id>/',views.del_question,name='del'),
    path('quesmodel/',views.QuestionModelCreateView.as_view(),name='quesmodel'),
    path('listmodel/',views.QuestionModelListView.as_view(),name='listmodel')
]

requor/urls.py
from django.contrib import admin
from django.urls import path,include 
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('qnaapp/',include ("qna_app.urls")),
    path('userapp/',include("user_app.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_app/urls.py
from django.urls import path,include

urlpatterns=[
   # path('',"userapp")
    
]

qna_app/models.py
from django.db import models

# Create your models here.
class CategoryModel(models.Model):
    cat_title=models.CharField(max_length=255)
    cat_desc=models.TextField()
    #objects=object.models.manager()
     
    def __str__(self):
        return self.cat_title


class QuestionModel(models.Model):
    title = models.CharField(max_length=255)
    posted_by = models.CharField(max_length=120)
    timestamp= models.DateTimeField(auto_now_add=True)
    question_desc= models.TextField()
    ques_img=models.ImageField(upload_to="QuestionImg",blank=True,null=True)
    ques_votes=models.IntegerField(default=0)
    #objects=object.models.manager()
    
    ques_cat=models.ForeignKey(CategoryModel,on_delete=models.CASCADE,null=True)

    def __str__(self):
        return(self.title)



class AnswerModel(models.Model):
    answer_by= models.CharField(max_length=255)
    timestamp= models.DateTimeField(auto_now_add=True)
    ans_desc= models.TextField()
    ans_img=models.ImageField(upload_to="AnswerImg",blank=True,null=True)
    ans_votes=models.IntegerField(default=0)
    isaccept=models.BooleanField(default=0)
    question= models.ForeignKey(QuestionModel,on_delete=models.CASCADE)
    #ans_cat=models.ForeignKey(CategoryModel,on_delete=models.CASCADE,null=True)

    def __str__(self):
        return(self.answer_by)


    

user_app/models.py
from django.db import models

# Create your models here.

qna_app/forms.py
from django import forms
from .models import QuestionModel,AnswerModel

class QuestionForm(forms.ModelForm):
    class Meta:             #change attribute of parent form
        model= QuestionModel
        fields='__all__'

qna_app/views.py
from django.shortcuts import render,redirect
from .models import QuestionModel,AnswerModel,CategoryModel
from .forms import QuestionForm
from django.http import HttpResponse
from django.views.generic import CreateView
from django.views.generic import ListView

class QuestionModelCreateView(CreateView):
    model=QuestionModel
    fields='__all__'

class QuestionModelListView(ListView):
    model=QuestionModel
    queryset=QuestionModel.objects.all()


# Create your views here.
def addquestion(request):
    if request.method=="POST":
        form=QuestionForm(request.POST,request.FILES) #request.files is for images
        if form.is_valid():
            try:
                form.save()
                return HttpResponse('Submitted')
            except:
                return HttpResponse('Failed')
        else:
            return HttpResponse(form.errors)
    else:
        #form= QuestionForm
        category= CategoryModel.objects.all()
    #question=QuestionModel.objects.all()
        return render(request,'questionmodel_create.html',{'cat':category})

def popques(request):
    pop=QuestionModel.objects.filter(ques_votes__gt=2)
    return render(request,'popques.html',{'p':pop})

def question(request):
    ques=QuestionModel.objects.all()
    return render(request,'question.html',{'q':ques})

def queslist(request):
    queslist=QuestionModel.objects.all()
    return render(request,'questionmodel_list.html',{'queslist':queslist})

def update_question(request,id):
    question= QuestionModel.objects.get(id=id)
    if request.method=="POST":
        form=QuestionForm(request.POST,request.FILES,instance=question) #request.files is for images
        if form.is_valid():
            try:
                form.save()
                return redirect('qna:update', id)
            except:
                return HttpResponse('Failed')
        else:
            return HttpResponse(form.errors)
    else:
        form= QuestionForm(instance=question)
    #question=QuestionModel.objects.all()
        return render(request,'questionmodel_update.html',{'form':form})



def del_question(request,id):
    question= QuestionModel.objects.get(id=id)
    question.delete()
    # return HttpResponse("deletequestionmodel_list.html")
    #question=QuestionModel.objects.all()
    return redirect('qna:queslist')

user_app/views.py
from django.shortcuts import render

# Create your views here.

qna_app/templates/newquestion.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title></title>
</head>
<body>
    This is a question form.
    {% for q in d %}
        <h2>{{q.title}}</h2>
        <h3>{{q.ques_desc}}</h3>
        <h3>{{q.timestamp}}</h3>
       {% if q.ques_img %}
        <img src="../../media/{{q.ques_img}}" height="100px" width="100px" >
{% endif %}
    {% endfor %}
</body>
</html>

qna_app/templates/popques.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Popular Question</title>
    <style>
            table, th, td {
              border: 1px solid black;
              border-collapse: collapse;
            }
            th, td {
              padding: 15px;
              text-align: left;
            }
            table#t01 {
              width: 100%;    
              background-color: #f1f1c1;
            }
    </style>
</head>
<body>
        <h1>This is the table.</h1>
        
    <table id="t01">
        <th></th>
        {% for q in p %}
        
        <tr>
            <td>
                
                <h2>{{q.title}}</h2>
                <h3><b>{{q.posted_by}}, {{ques.timestamp|date:'Y-M-D  h-m-s P'}}</b>
                
                {{q.desc|truncatechars:50}}
                <br>
                {% if q.ques_img %}
                <img src="../../media/{{q.ques_img}}" height="100px" width="100px" >        
                {% endif %}
                
                <br>
                Votes: {{q.ques_votes}}

                <br>

                    
                 {{q.ques_cat}}

            </td>
            <br>
        </tr>

        {% endfor %}
    </table>
</body>
</html>

qna_app/templates/qna_app/questionmodel_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    J lekhe ni hunxa re
</body>
</html>

qna_app/templates/qna_app/questionmodel_list.html
{{object_list}}

qna_app/templates/question.html
{{ q }}

qna_app/templates/questionmodel_create.html
<form method="POST" enctype="multipart/form-data"> 
    {% csrf_token %}
    {{form.errors}}
    Title:<input type="text" name="title" > <br><br>
    posted_by<input type="text" name="posted_by"><br><br>
     Description:<input type="text" name="question_desc"><br><br>
     Image:<input type="file" name="ques_img"><br><br>
     Category:<select name=" ques_cat">
            {% for c in cat %}
            <option value="{{c.id}}">{{c.cat_title}}</option>
           {% endfor %}
           </select>
        <br>  
     <input type="hidden" name="ques_votes" value="0">
<br> <br>
     <input type="submit" value="submit">
</form>

     

qna_app/templates/questionmodel_delete.html
<form method="POST" enctype="multipart/form-data"> 
    {% csrf_token %}
    {{ form }}
    <button type="submit" value="submit">Delete</button>

</form>

qna_app/templates/questionmodel_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title></title>
</head>
<body>
    This is a question form.
    <a href="{%url 'qna:add' %}"><button>Add Question</button></a>
    {% for q in queslist %}
        <h2>{{q.title}}</h2>
        <h3>{{q.ques_desc}}</h3>
        <h3>{{q.timestamp}}</h3>
       {% if q.ques_img %}
        <img src="../../media/{{q.ques_img}}" height="100px" width="100px" >
{% endif %}
<a href="{%url 'qna:update' q.id %}"><button>Update</button></a>
<a href="{%url 'qna:del' q.id %}"><button>Delete</button></a>

{% endfor %}



</body>
</html>

qna_app/templates/questionmodel_update.html
<form method="POST" enctype="multipart/form-data"> 
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="submit">

</form>